### ISSUE TITLE
portal没有被优先使用，x11下无法启动服务

### ISSUE THREAD

**Issue by detiam** [Decodetalkers/xdg-desktop-portal-shana#2]
```
$ systemctl status --user xdg-desktop-portal-shana.service
○ xdg-desktop-portal-shana.service - Portal service (wlroots implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-shana.service; static)
     Active: inactive (dead)

4月 14 09:51:48 Tinkling-PC systemd[897]: Portal service (wlroots implementation) was skipped because of an unmet condition check (ConditionEnvironment=WAYLAND_DISPLAY).
```
DE: KDE Plasma 5.27.4
WM: KWin (X11)

**Comment by Decodetalkers** [comment]
哦，我service里面添加了wayland,你直接跑这个二进制也可以。。不过kde有自己的filechooser啊

**Comment by detiam** [comment]
> 哦，我service里面添加了wayland,你直接跑这个二进制也可以。。不过kde有自己的filechooser啊

qt6和gtk程序还是用程序自带的那个filechooser，比较不统一而且看不到自己设置的收藏夹，
只安装`xdg-desktop-portal-kde`开机在`/etc/environment`设置环境变量`QT_QPA_PLATFORMTHEME=xdgdesktopportal`
的话开文件夹又莫名奇妙卡死。。在找办法解决这个奇怪的问题

<hr>

`ConditionEnvironment=WAYLAND_DISPLAY`删了重启，但 tg 还是用`xdg-desktop-portal-kde` 这个portal，删了就变成 `xdg-desktop-portal-gnome` 的了。而不是在`~/.config/xdg-desktop-portal-shana/config.toml`里设置的Gtk，xdg-desktop-portal有办法设置使用哪个portal或者设置优先级吗

**Comment by Decodetalkers** [comment]
> > 哦，我service里面添加了wayland,你直接跑这个二进制也可以。。不过kde有自己的filechooser啊
> 
> qt6和gtk程序还是用程序自带的那个filechooser，比较不统一而且看不到自己设置的收藏夹， 只安装`xdg-desktop-portal-kde`开机在`/etc/environment`设置环境变量`QT_QPA_PLATFORMTHEME=xdgdesktopportal` 的话开文件夹又莫名奇妙卡死。。在找办法解决这个奇怪的问题
> 
> `ConditionEnvironment=WAYLAND_DISPLAY`删了重启，但 tg 还是用`xdg-desktop-portal-kde` 这个portal，删了就变成 `xdg-desktop-portal-gnome` 的了。而不是在`~/.config/xdg-desktop-portal-shana/config.toml`里设置的Gtk，xdg-desktop-portal有办法设置使用哪个portal或者设置优先级吗

kde 在命名顺序上， k > s ,所以优先使用的它。。除非服务改成a开头才会优先匹配到这个，portal这点比较麻烦。。

**Comment by Decodetalkers** [comment]
你要不试验下，rename那个portal名字让它在字典序最前面，这样它就优先匹配到了

**Comment by detiam** [comment]
可是gnome不是 g > k  ，结果还是优先用kde的。
不过 kde 的 FileChooser 删了就直接就用 shana 的了

> 或者那个服务的名词shana.portal 改成ashana.portal我想也是可以的，然后重启Xdg-desktop-protal 服务

shana.portal 改叫 above-all-shana.portal， 有点`the portal of portal`的风范 🤣

**Comment by Decodetalkers** [comment]
> 可是gnome不是 g > k  ，结果还是优先用kde的。
> 不过 kde 的 FileChooser 删了就直接就用 shana 的了
> 
> > 或者那个服务的名词shana.portal 改成ashana.portal我想也是可以的，然后重启Xdg-desktop-protal 服务
> 
> shana.portal 改叫 above-all-shana.portal， 有点`the portal of portal`的风范 🤣
> 
> 

那是Gnome的portal沒有声明可以在kde上使用，所以它当然不会被主动调用，不过从shana走一圈就可以用了

**Comment by Decodetalkers** [comment]
这个你就可以pr啊，如果你想的话你不是知道怎么处理了吗

不过对于优先使用，我不知道是不是应该抢占kde和gnome的服务，让字典序在前面，不过service去掉对wayland的依赖还是没有问题的

**Comment by detiam** [comment]
@Decodetalkers  更新一下，现在似乎可以[配置用哪个FileChooser](https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst#example)，比如现在我的配置是：
```Properties
[preferred]
default=*
org.freedesktop.impl.portal.FileChooser=shana
```

**Comment by Decodetalkers** [comment]
> @Decodetalkers 补充一下，现在似乎可以[配置用哪个FileChooser](https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst#example)，比如现在我的配置是：
> 
> ```ini
> [preferred]
> default=*
> org.freedesktop.impl.portal.FileChooser=shana
> ```

還沒發佈呢，這個還不能用，現在還是字典序
